
[workspace]
members = [
	"extern-reader",
	"install-externs",
	"temportal-math",
	"temportal-graphics",
	"temportal-engine", "temportal-engine-editor",
	"demo-triangle", "demo-triangle-editor",
	"boid", "boid-editor",
	"crystal-sphinx", "crystal-sphinx-editor"
]
default-members = [
	"temportal-math",
	"demo-triangle", "demo-triangle-editor",
	"boid", "boid-editor",
	"crystal-sphinx", "crystal-sphinx-editor",
]
