
[workspace]
members = [
	"extern-reader",
	"install-externs",
	"temportal-math",
	"temportal-graphics",
	"temportal-engine",
	"temportal-engine-editor",
	"demo-triangle",
	"demo-triangle-editor"
]
default-members = ["demo-triangle"]
